import Link from "next/link";
import { ArrowUpRight, Sparkles, ThumbsUp } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Avatar } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Surface } from "@/components/ui/surface";
import { games, optimizations } from "@/lib/mock-data";

export default function BlueprintsPage() { return <AppShell><div className="min-h-[calc(100vh-72px)] px-5 py-8 lg:px-9 lg:py-10"><div className="mx-auto max-w-[1240px]"><p className="text-[11px] font-bold uppercase tracking-[.18em] text-cyan">Community intelligence</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-white">Performance Blueprints</h1><p className="mt-2 max-w-xl text-sm leading-6 text-muted">Reliable settings from real players, sorted for your hardware and your target frame rate.</p><div className="mt-8 grid gap-4 lg:grid-cols-3">{optimizations.map((item) => { const game = games.find((g) => g.id === item.gameId)!; return <Surface key={item.id} className="p-5"><div className="flex items-start justify-between"><div className="flex items-center gap-3"><Avatar initials={item.initials} /><div><p className="text-sm font-semibold text-white">{item.username}</p><p className="text-[10px] text-muted">{game.title}</p></div></div><Badge tone="violet"><Sparkles size={11} className="mr-1" /> tuned</Badge></div><div className="mt-5 grid grid-cols-2 gap-2"><div className="rounded-lg bg-white/[.03] p-3"><p className="text-[10px] uppercase tracking-[.12em] text-muted">Hardware</p><p className="mt-1 text-xs font-semibold text-white">{item.gpuModel}</p></div><div className="rounded-lg bg-white/[.03] p-3"><p className="text-[10px] uppercase tracking-[.12em] text-muted">Target</p><p className="mt-1 text-xs font-semibold text-white">{item.resolution} · {item.targetFps} FPS</p></div></div><div className="mt-4 flex items-center justify-between border-t border-border/60 pt-4"><span className="flex items-center gap-1.5 text-xs text-muted"><ThumbsUp size={13} /> {item.upvotes} upvotes</span><Link href={`/games/${game.id}`} className="flex items-center gap-1 text-xs font-semibold text-cyan">View setup <ArrowUpRight size={13} /></Link></div></Surface>; })}</div></div></div></AppShell>; }
