"use client";

import Link from "next/link";
import { useActionState } from "react";
import { ArrowRight, GitBranch, LockKeyhole, Mail, Zap } from "lucide-react";
import { signIn, signInWithGithub, signUp } from "@/actions/auth";
import { Button } from "@/components/ui/button";

type AuthState = { error?: string; success?: string };
const initialState: AuthState = {};

export function AuthForm() {
  const [state, action, pending] = useActionState<AuthState, FormData>(signIn, initialState);
  return <div className="min-h-screen bg-[#080a0d] text-foreground lg:grid lg:grid-cols-[1.05fr_.95fr]">
    <AuthBrand />
    <div className="flex items-center justify-center px-6 py-12"><div className="w-full max-w-[390px]">
      <div className="mb-10 flex items-center gap-2.5 lg:hidden"><Logo /></div>
      <p className="text-[11px] font-bold uppercase tracking-[.18em] text-cyan">Welcome back</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-white">Sign in to your hub</h2><p className="mt-2 text-sm text-muted">Your next great session starts here.</p>
      <form action={action} className="mt-8 space-y-5"><label className="block"><span className="text-xs font-semibold text-[#cdd5dc]">Email address</span><span className="relative mt-2 block"><Mail size={15} className="absolute left-3 top-3 text-muted" /><input name="email" type="email" required placeholder="you@example.com" className="h-11 w-full rounded-lg border border-border bg-panel pl-10 pr-3 text-sm text-white outline-none placeholder:text-[#5b6874] focus:border-cyan/60" /></span></label><label className="block"><span className="flex items-center justify-between text-xs font-semibold text-[#cdd5dc]"><span>Password</span><a href="#" className="font-medium text-cyan hover:text-white">Forgot password?</a></span><span className="relative mt-2 block"><LockKeyhole size={15} className="absolute left-3 top-3 text-muted" /><input name="password" type="password" required placeholder="8+ characters" className="h-11 w-full rounded-lg border border-border bg-panel pl-10 pr-3 text-sm text-white outline-none placeholder:text-[#5b6874] focus:border-cyan/60" /></span></label>{(state.error || state.success) && <p className={state.error ? "text-xs text-red-300" : "text-xs text-emerald-300"}>{state.error ?? state.success}</p>}<Button type="submit" className="h-11 w-full" disabled={pending}>{pending ? "Signing you in..." : "Continue"}<ArrowRight size={15} /></Button></form>
      <div className="my-7 flex items-center gap-3 text-[10px] uppercase tracking-[.16em] text-muted"><span className="h-px flex-1 bg-border" />or continue with<span className="h-px flex-1 bg-border" /></div><form action={async () => { await signInWithGithub(); }}><Button type="submit" variant="secondary" className="h-11 w-full"><GitBranch size={16} /> GitHub</Button></form><p className="mt-8 text-center text-xs text-muted">New to OptiSync? <Link href="/auth/register" className="font-semibold text-cyan hover:text-white">Create an account</Link></p><p className="mt-12 text-center text-[10px] leading-5 text-[#56616c]">By continuing, you agree to our Terms of Service<br />and acknowledge our Privacy Policy.</p>
    </div></div>
  </div>;
}

export function RegisterForm() {
  const [state, action, pending] = useActionState<AuthState, FormData>(signUp, initialState);
  return <div className="min-h-screen bg-[#080a0d] text-foreground"><div className="mx-auto flex min-h-screen max-w-[480px] items-center px-6 py-12"><div className="w-full"><Link href="/" className="flex items-center gap-2.5 text-lg font-bold"><Logo /></Link><p className="mt-12 text-[11px] font-bold uppercase tracking-[.18em] text-cyan">Start your baseline</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-white">Create your OptiSync account</h1><p className="mt-2 text-sm text-muted">Build a library that learns how you play.</p><form action={action} className="mt-8 space-y-5"><label className="block"><span className="text-xs font-semibold text-[#cdd5dc]">Email address</span><input name="email" type="email" required className="mt-2 h-11 w-full rounded-lg border border-border bg-panel px-3 text-sm text-white outline-none focus:border-cyan/60" /></label><label className="block"><span className="text-xs font-semibold text-[#cdd5dc]">Password</span><input name="password" type="password" required className="mt-2 h-11 w-full rounded-lg border border-border bg-panel px-3 text-sm text-white outline-none focus:border-cyan/60" /></label>{(state.error || state.success) && <p className={state.error ? "text-xs text-red-300" : "text-xs text-emerald-300"}>{state.error ?? state.success}</p>}<Button className="h-11 w-full" disabled={pending}>{pending ? "Creating account..." : "Create account"}<ArrowRight size={15} /></Button></form><p className="mt-8 text-center text-xs text-muted">Already have an account? <Link href="/auth/login" className="font-semibold text-cyan">Sign in</Link></p></div></div></div>;
}

function Logo() { return <><span className="grid size-8 place-items-center rounded-lg bg-cyan text-[#071013]"><Zap size={17} fill="currentColor" /></span>Opti<span className="text-cyan">Sync</span></>; }

function AuthBrand() { return <div className="grid-texture relative hidden overflow-hidden border-r border-border/70 p-12 lg:flex lg:flex-col lg:justify-between xl:p-20"><div className="absolute -left-24 top-20 size-80 rounded-full bg-cyan/10 blur-[110px]" /><div className="absolute bottom-0 right-0 size-96 rounded-full bg-purple/10 blur-[120px]" /><div className="relative flex items-center gap-2.5"><Logo /></div><div className="relative max-w-lg"><p className="text-[11px] font-bold uppercase tracking-[.2em] text-cyan">Performance intelligence for PC gamers</p><h1 className="mt-6 text-5xl font-semibold leading-[1.08] tracking-[-.04em] text-white xl:text-6xl">Your library.<br /><span className="text-muted">Tuned to you.</span></h1><p className="mt-7 max-w-md text-base leading-7 text-muted">Stop chasing settings after every patch. OptiSync turns live game updates and community expertise into a setup that simply works.</p><div className="mt-12 grid max-w-md grid-cols-3 gap-6 border-t border-border/70 pt-6"><div><p className="text-xl font-semibold text-white">12k+</p><p className="mt-1 text-xs text-muted">blueprints shared</p></div><div><p className="text-xl font-semibold text-white">184</p><p className="mt-1 text-xs text-muted">games indexed</p></div><div><p className="text-xl font-semibold text-white">99.8%</p><p className="mt-1 text-xs text-muted">sync uptime</p></div></div></div><p className="relative text-xs text-[#58636e]">© 2026 OptiSync Labs · Built for better frames</p></div>; }
