"use client";

import Link from "next/link";
import Image from "next/image";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowLeft, Check, ChevronDown, Clock3, Cpu, ExternalLink, Flame, Plus, Settings2, Sparkles, Target, ThumbsUp, X } from "lucide-react";
import { useState } from "react";
import { AppShell } from "@/components/app-shell";
import { Avatar } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Surface } from "@/components/ui/surface";
import { games, getGameOptimizations, getGamePatches } from "@/lib/mock-data";
import { cn } from "@/lib/utils";

export function GameDetail({ gameId }: { gameId: string }) {
  const game = games.find((item) => item.id === gameId) ?? games[0];
  const gamePatches = getGamePatches(game.id);
  const gameOptimizations = getGameOptimizations(game.id);
  const [tab, setTab] = useState<"patches" | "optimizations">("patches");
  const [dialogOpen, setDialogOpen] = useState(false);
  return <AppShell><div className="min-h-[calc(100vh-72px)] px-5 py-7 lg:px-9 lg:py-9"><div className="mx-auto max-w-[1240px]">
    <Link href="/" className="mb-6 inline-flex items-center gap-2 text-xs font-semibold text-muted hover:text-cyan"><ArrowLeft size={14} /> Back to Patch Radar</Link>
    <div className="relative overflow-hidden rounded-2xl border border-border/80"><Image src={game.coverImageUrl} alt="" fill sizes="100vw" className="object-cover opacity-25 blur-[1px]" /><div className="absolute inset-0 bg-gradient-to-r from-[#0b0e12] via-[#0b0e12]/90 to-[#0b0e12]/55" /><div className="absolute inset-0 bg-gradient-to-t from-[#0b0e12] via-transparent to-transparent" /><div className="relative flex min-h-[260px] items-end p-6 md:min-h-[300px] md:p-9"><div><div className="flex flex-wrap items-center gap-2"><Badge tone="green"><span className="mr-1 size-1.5 rounded-full bg-emerald-300" /> Tracking active</Badge><Badge>{game.genre}</Badge><span className="text-xs text-muted">Steam App {game.steamAppId}</span></div><h1 className="mt-4 text-3xl font-semibold tracking-tight text-white md:text-5xl">{game.title}</h1><p className="mt-3 max-w-xl text-sm leading-6 text-[#a4afb8]">Your performance intelligence center. Compare community blueprints and stay ahead of every patch.</p></div><div className="absolute bottom-7 right-7 hidden items-center gap-2 md:flex"><div className="rounded-lg border border-white/10 bg-black/30 px-4 py-3 backdrop-blur"><p className="text-[10px] uppercase tracking-[.14em] text-muted">Latest patch</p><p className="mt-1 text-sm font-semibold text-white">v{gamePatches[0]?.version ?? "1.0"}</p></div><div className="rounded-lg border border-white/10 bg-black/30 px-4 py-3 backdrop-blur"><p className="text-[10px] uppercase tracking-[.14em] text-muted">Blueprints</p><p className="mt-1 text-sm font-semibold text-white">{gameOptimizations.length + 24}</p></div></div></div></div>
    <div className="mt-7 flex items-center gap-1 border-b border-border/70"><Tab active={tab === "patches"} onClick={() => setTab("patches")} icon={Clock3}>Patch notes <span className="ml-1 text-[10px] text-muted">{gamePatches.length}</span></Tab><Tab active={tab === "optimizations"} onClick={() => setTab("optimizations")} icon={Sparkles}>Optimizations <span className="ml-1 text-[10px] text-muted">{gameOptimizations.length + 24}</span></Tab></div>
    <AnimatePresence mode="wait"><motion.div key={tab} initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -6 }} transition={{ duration: .18 }} className="mt-7">{tab === "patches" ? <PatchNotes patches={gamePatches} /> : <Blueprints optimizations={gameOptimizations} onSubmit={() => setDialogOpen(true)} />}</motion.div></AnimatePresence>
  </div></div>{dialogOpen && <BlueprintDialog onClose={() => setDialogOpen(false)} />}</AppShell>;
}

function Tab({ active, onClick, icon: Icon, children }: { active: boolean; onClick: () => void; icon: typeof Clock3; children: React.ReactNode }) { return <button onClick={onClick} className={cn("relative flex items-center gap-2 px-4 pb-3 text-sm font-semibold transition-colors", active ? "text-cyan" : "text-muted hover:text-white")}>{<Icon size={15} />}{children}{active && <span className="absolute inset-x-0 -bottom-px h-px bg-cyan shadow-[0_0_8px_#63e6ef]" />}</button>; }

function PatchNotes({ patches }: { patches: ReturnType<typeof getGamePatches> }) { return <div className="grid gap-4">{patches.map((patch, index) => <Surface key={patch.id} className="p-5 md:p-6"><div className="flex flex-col justify-between gap-4 md:flex-row"><div className="flex items-center gap-3"><div className={cn("grid size-10 place-items-center rounded-lg", patch.isHotfix ? "bg-emerald-400/10 text-emerald-300" : "bg-cyan/10 text-cyan")}><Settings2 size={18} /></div><div><div className="flex items-center gap-2"><h2 className="text-base font-semibold text-white">{patch.title}</h2><Badge tone={patch.isHotfix ? "green" : "blue"}>{patch.isHotfix ? "Hotfix" : "Update"}</Badge></div><p className="mt-1 text-xs text-muted">Released {new Date(patch.releaseDate).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })} · v{patch.version}</p></div></div><a href="#" className="flex items-center gap-1.5 self-start text-xs font-semibold text-cyan hover:text-white">Read full notes <ExternalLink size={13} /></a></div><p className="mt-5 max-w-3xl text-sm leading-6 text-muted">{patch.summary}</p><div className="mt-5 flex flex-wrap gap-2">{patch.tags.map((tag) => <span key={tag} className="rounded-md border border-border bg-white/[.025] px-2.5 py-1.5 text-xs text-[#b4bec7]">{tag}</span>)}</div>{index === 0 && <div className="mt-5 flex items-center gap-2 border-t border-border/60 pt-4 text-xs text-orange-300"><Flame size={14} /> This update may affect your current blueprint. Review recommended.</div>}</Surface>)}</div>; }

function Blueprints({ optimizations, onSubmit }: { optimizations: ReturnType<typeof getGameOptimizations>; onSubmit: () => void }) { return <div><div className="mb-5 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="text-lg font-semibold text-white">Community blueprints</h2><p className="mt-1 text-xs text-muted">Settings tuned by players with similar hardware.</p></div><Button onClick={onSubmit}><Plus size={15} /> Submit blueprint</Button></div><div className="grid gap-4">{optimizations.map((item) => <Surface key={item.id} className="p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start"><div className="flex items-center gap-3 lg:w-52"><Avatar initials={item.initials} /><div><p className="text-sm font-semibold text-white">{item.username}</p><p className="mt-0.5 text-[11px] text-muted">Verified setup</p></div></div><div className="grid flex-1 gap-3 sm:grid-cols-3"><Metric icon={Cpu} label="GPU" value={item.gpuModel} /><Metric icon={Target} label="Resolution" value={item.resolution} /><Metric icon={GaugeIcon} label="Target FPS" value={`${item.targetFps} FPS`} /></div><button className="flex items-center gap-2 self-start rounded-lg border border-border px-3 py-2 text-xs font-semibold text-muted hover:border-cyan/40 hover:text-cyan"><ThumbsUp size={14} /> {item.upvotes}</button></div><div className="mt-5 grid gap-2 border-t border-border/60 pt-4 sm:grid-cols-2 lg:grid-cols-5">{Object.entries(item.settings).map(([key, value]) => <div key={key} className="rounded-lg bg-white/[.025] px-3 py-2"><p className="text-[10px] uppercase tracking-[.12em] text-muted">{key}</p><p className="mt-1 text-xs font-semibold text-[#d7dfe5]">{value}</p></div>)}</div></Surface>)}</div></div>; }

const GaugeIcon = Target;
function Metric({ icon: Icon, label, value }: { icon: typeof Cpu; label: string; value: string }) { return <div className="rounded-lg border border-border/70 bg-[#0d1116] px-3 py-2.5"><div className="flex items-center gap-1.5 text-[10px] uppercase tracking-[.13em] text-muted"><Icon size={12} />{label}</div><p className="mt-1.5 text-xs font-semibold text-white">{value}</p></div>; }

function BlueprintDialog({ onClose }: { onClose: () => void }) { const [submitted, setSubmitted] = useState(false); return <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4 backdrop-blur-sm"><motion.div initial={{ opacity: 0, scale: .97 }} animate={{ opacity: 1, scale: 1 }} className="w-full max-w-xl rounded-2xl border border-border bg-[#11161c] p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-cyan">Performance blueprint</p><h2 className="mt-2 text-xl font-semibold text-white">Share your setup</h2><p className="mt-1 text-xs text-muted">Help players with similar hardware find their sweet spot.</p></div><button onClick={onClose} className="text-muted hover:text-white" aria-label="Close dialog"><X size={18} /></button></div>{submitted ? <div className="py-12 text-center"><div className="mx-auto grid size-12 place-items-center rounded-full bg-emerald-400/10 text-emerald-300"><Check size={22} /></div><h3 className="mt-4 text-lg font-semibold text-white">Blueprint submitted</h3><p className="mt-2 text-sm text-muted">Your settings are now ready for the community.</p><Button className="mt-6" onClick={onClose}>Close</Button></div> : <form className="mt-7 space-y-5" onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }}><div className="grid gap-4 sm:grid-cols-2"><Field label="GPU model" value="RTX 4070" /><Field label="Resolution" value="1440p" /><Field label="Target FPS" value="90" /><Field label="DLSS / FSR" value="Quality" /></div><div><label className="text-xs font-semibold text-[#cdd5dc]">Settings snapshot</label><textarea className="mt-2 min-h-28 w-full resize-none rounded-lg border border-border bg-[#0b0e12] p-3 text-sm text-white outline-none placeholder:text-muted focus:border-cyan/60" placeholder="Shadows: High\nRay Tracing: Medium\nFrame Generation: On" defaultValue="Shadows: High\nRay Tracing: Medium\nFrame Generation: On" /></div><div className="flex justify-end gap-2 border-t border-border/60 pt-5"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit"><Sparkles size={14} /> Publish blueprint</Button></div></form>}</motion.div></div>; }
function Field({ label, value }: { label: string; value: string }) { return <div><label className="text-xs font-semibold text-[#cdd5dc]">{label}</label><div className="mt-2 flex h-10 items-center justify-between rounded-lg border border-border bg-[#0b0e12] px-3 text-sm text-white">{value}<ChevronDown size={14} className="text-muted" /></div></div>; }
