"use client";

import Link from "next/link";
import Image from "next/image";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowUpRight, CalendarDays, ChevronRight, CircleDot, Download, Filter, Gauge, MoreHorizontal, Radio, RefreshCw } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Surface } from "@/components/ui/surface";
import { games, patches } from "@/lib/mock-data";
import { cn, formatRelativeDate } from "@/lib/utils";
import type { Patch, UpdateKind } from "@/types/domain";

function updateKind(patch: Patch): UpdateKind {
  if (patch.isHotfix || patch.updateSizeMb < 100) return "hotfix";
  if (patch.updateSizeMb >= 5120) return "major";
  return "standard";
}

function UpdateBadge({ patch }: { patch: Patch }) {
  const kind = updateKind(patch);
  return <Badge tone={kind === "hotfix" ? "green" : kind === "major" ? "orange" : "blue"}>{kind === "hotfix" ? "Hotfix" : kind === "major" ? "Major patch" : "Standard update"}</Badge>;
}

function sizeLabel(size: number) { return size >= 1024 ? `${(size / 1024).toFixed(1)} GB` : `${size} MB`; }

export function PatchRadar() {
  const [filter, setFilter] = useState<"all" | UpdateKind>("all");
  const visible = patches.filter((patch) => filter === "all" || updateKind(patch) === filter);
  return <div className="grid-texture min-h-[calc(100vh-72px)] px-5 py-8 lg:px-9 lg:py-10"><div className="mx-auto max-w-[1440px]">
    <div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><div className="mb-3 flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.18em] text-cyan"><Radio size={13} /> Live intelligence feed</div><h1 className="text-3xl font-semibold tracking-tight text-white lg:text-4xl">Patch Radar</h1><p className="mt-2 max-w-xl text-sm leading-6 text-muted">A clear signal through the noise. Track what changed, what matters, and how it affects your rig.</p></div><div className="flex items-center gap-2"><button onClick={() => toast.success("Library sync queued", { description: "We will check Steam for new patch signals." })} className="inline-flex h-9 items-center gap-2 rounded-lg border border-border bg-panel px-3 text-xs font-medium text-muted hover:text-foreground"><RefreshCw size={13} /> Sync library</button><button onClick={() => toast("Rig tuner is ready", { description: "Open a game to compare performance blueprints." })} className="inline-flex h-9 items-center gap-2 rounded-lg bg-cyan px-3 text-xs font-bold text-[#071013] shadow-[0_0_22px_rgba(99,230,239,.13)]"><Gauge size={14} /> Tune my rig</button></div></div>
    <div className="mt-9 grid gap-3 sm:grid-cols-3"><Stat label="Tracked games" value="12" detail="3 updates this week" icon={Gauge} tone="cyan" /><Stat label="Patches this month" value="28" detail="+18% vs last month" icon={Download} tone="violet" /><Stat label="Blueprints saved" value="07" detail="2 need review" icon={CircleDot} tone="orange" /></div>
    <div className="mt-10 flex flex-col justify-between gap-4 border-b border-border/70 pb-4 sm:flex-row sm:items-center"><div><h2 className="text-lg font-semibold text-white">Latest signals</h2><p className="mt-1 text-xs text-muted">Updates from your tracked library</p></div><div className="flex items-center gap-1.5"><Filter size={14} className="mr-1 text-muted" />{(["all", "hotfix", "standard", "major"] as const).map((value) => <button key={value} onClick={() => setFilter(value)} className={cn("rounded-md px-2.5 py-1.5 text-[11px] font-semibold capitalize transition-colors", filter === value ? "bg-white/[.09] text-white" : "text-muted hover:text-foreground")}>{value === "all" ? "All updates" : value}</button>)}</div></div>
    <div className="mt-6 grid gap-7 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="relative ml-2 border-l border-border/80 pl-7 md:pl-10"><AnimatePresence mode="popLayout">{visible.map((patch, index) => { const game = games.find((item) => item.id === patch.gameId)!; return <motion.article key={patch.id} layout initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, scale: .98 }} transition={{ duration: .22, delay: index * .03 }} className="relative mb-5 last:mb-0"><span className="absolute -left-[35px] top-6 size-2 rounded-full border-2 border-background bg-cyan shadow-[0_0_0_4px_rgba(99,230,239,.1),0_0_14px_#63e6ef] md:-left-[47px]" /><Surface className="overflow-hidden transition-colors hover:border-[#3a4855]"><div className="flex flex-col gap-5 p-5 sm:flex-row sm:items-start"><div className="relative h-24 w-full shrink-0 overflow-hidden rounded-lg sm:w-40"><Image src={game.coverImageUrl} alt="" fill sizes="160px" className="object-cover opacity-80" /><div className="absolute inset-0 bg-gradient-to-r from-black/40 to-transparent" /><div className="absolute bottom-2 left-2"><Badge className="border-white/20 bg-black/60 text-white">{game.title}</Badge></div></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><UpdateBadge patch={patch} /><span className="text-xs text-muted">{formatRelativeDate(patch.releaseDate)}</span><span className="text-[#44505b]">•</span><span className="text-xs text-muted">v{patch.version}</span></div><h3 className="mt-3 text-lg font-semibold text-white">{patch.title}</h3><p className="mt-1.5 max-w-2xl text-sm leading-6 text-muted">{patch.summary}</p><div className="mt-4 flex flex-wrap items-center gap-2">{patch.tags.map((tag) => <span key={tag} className="rounded border border-border px-2 py-1 text-[10px] font-medium text-[#aab4bd]">{tag}</span>)}<span className="ml-auto flex items-center gap-1.5 text-xs text-muted"><Download size={13} /> {sizeLabel(patch.updateSizeMb)}</span></div></div><button aria-label="More patch actions" className="hidden text-muted hover:text-white sm:block"><MoreHorizontal size={18} /></button></div><div className="flex items-center justify-between border-t border-border/60 bg-white/[.015] px-5 py-3"><span className="flex items-center gap-2 text-[11px] text-muted"><CalendarDays size={13} /> Released {new Date(patch.releaseDate).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}</span><Link href={`/games/${game.id}`} className="flex items-center gap-1 text-[11px] font-bold text-cyan hover:text-white">View game intelligence <ArrowUpRight size={13} /></Link></div></Surface></motion.article>; })}</AnimatePresence></div>
      <aside className="space-y-4"><Surface className="p-5"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-muted">Library pulse</p><h3 className="mt-2 text-base font-semibold text-white">Your games are healthy</h3></div><div className="grid size-9 place-items-center rounded-lg bg-emerald-400/10 text-emerald-300"><Gauge size={17} /></div></div><div className="mt-6 flex items-end justify-between"><span className="text-3xl font-semibold text-white">92<span className="text-base text-muted">%</span></span><span className="text-xs text-emerald-300">+4.2% this week</span></div><div className="mt-3 h-2 rounded-full bg-white/[.06]"><div className="h-full w-[92%] rounded-full bg-gradient-to-r from-emerald-400 to-cyan" /></div><p className="mt-3 text-xs leading-5 text-muted">11 of 12 tracked games have a current performance blueprint.</p></Surface><Surface className="p-5"><div className="flex items-center justify-between"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-muted">Tracked library</p><Link href="/library" className="text-xs font-semibold text-cyan">Manage</Link></div><div className="mt-4 space-y-3">{games.map((game) => <Link href={`/games/${game.id}`} key={game.id} className="flex items-center gap-3 rounded-lg p-1.5 transition-colors hover:bg-white/[.04]"><img src={game.coverImageUrl} alt="" className="size-9 rounded-md object-cover" /><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold text-white">{game.title}</p><p className="mt-0.5 text-[10px] text-muted">{patches.filter((patch) => patch.gameId === game.id).length} recent signals</p></div><ChevronRight size={14} className="text-muted" /></Link>)}</div></Surface></aside></div>
  </div></div>;
}

function Stat({ label, value, detail, icon: Icon, tone }: { label: string; value: string; detail: string; icon: typeof Gauge; tone: "cyan" | "violet" | "orange" }) { return <Surface className="flex items-center gap-4 p-4"><div className={cn("grid size-10 place-items-center rounded-lg", tone === "cyan" ? "bg-cyan/10 text-cyan" : tone === "violet" ? "bg-purple/10 text-purple" : "bg-orange-400/10 text-orange-300")}><Icon size={18} /></div><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-muted">{label}</p><div className="mt-1 flex items-baseline gap-2"><span className="text-2xl font-semibold text-white">{value}</span><span className="text-[10px] text-emerald-300">{detail}</span></div></div></Surface>; }
